name: actions

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:     
      - uses: actions/checkout@v3
      - name: Instalar dependencias
        run:  composer install
      - name: Correr los tests
        run: ./vendor/bin/phpunit
      - name : Ejecutar grumphp
        run: ./vendor/bin/grumphp run
